### ISSUE TITLE
Minor updates to package imports

### ISSUE THREAD

**Issue by sushantveer** [irom-lab/panda_env_pybullet_irom#1]
There is not `utils` folder to be imported: https://github.com/irom-lab/panda_env_pybullet_irom/blob/80952b9b76f96af2178f5b35d5f591deb808b56a/panda_env.py#L2

Use relative imports for packages at https://github.com/irom-lab/panda_env_pybullet_irom/blob/80952b9b76f96af2178f5b35d5f591deb808b56a/panda_env.py#L9-L10, i.e., 
```python
from .utils_geom import *
from .panda import Panda
```

**Comment by allenzren** [comment]
pip install available now
